apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-autoscale
  namespace: "{{ gcp_namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  laravel-deployment
  minReplicas: 1
  maxReplicas: 3
  behavior:
  scaleDown:
    stabilizationWindowSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
