- name: Delete ConfigMap
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    namespace: "{{ gcp_namespace }}"
    name: config

- name: Delete Secrets
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: "{{ gcp_namespace }}"
    name: mysql-pass